### ISSUE TITLE
Error messages on startup

### ISSUE THREAD

**Issue by colva** [gap-packages/anatph#1]
When I type 
LoadPackage("anatph");

It successfully loads, but I get many syntax warnings:
#I  equal requirements in multiple declarations for operation `Merge'

#I  method installed for Size matches more than one declaration
#I  method installed for Base matches more than one declaration
#I  method installed for Exponent matches more than one declaration
#I  method installed for Length matches more than one declaration
Syntax warning: unbound global variable in /Applications/gap4r8/pkg/anatph/gap\
/examples.gi line 102
    start := NanosecondsSinceEpoch();
                                  ^
Syntax warning: unbound global variable in /Applications/gap4r8/pkg/anatph/gap\
/examples.gi line 107
        estart := NanosecondsSinceEpoch();
                                       ^
Syntax warning: unbound global variable in /Applications/gap4r8/pkg/anatph/gap\
/examples.gi line 109
        estop := NanosecondsSinceEpoch();
                                      ^
Syntax warning: unbound global variable in /Applications/gap4r8/pkg/anatph/gap\
/examples.gi line 118
    stop := NanosecondsSinceEpoch();
                                 ^
Syntax warning: unbound global variable in /Applications/gap4r8/pkg/anatph/gap\
/examples.gi line 250
    t := NanosecondsSinceEpoch();
                              ^
Syntax warning: unbound global variable in /Applications/gap4r8/pkg/anatph/gap\
/examples.gi line 252
    t := NanosecondsSinceEpoch() - t;
                              ^
Syntax warning: unbound global variable in /Applications/gap4r8/pkg/anatph/gap\
/examples.gi line 262
    OutputAnnotatedCodeCoverageFiles("anatph.gz", "/home/makx/tmp/anatph");
                                    ^
─────────────────────────────────────────────────────────────────────────────
Loading  anatph 0.2 (A new approach to proving hyperbolicity)
by Colva Roney-Dougal (),
   Derek Holt (),
   Richard Parker (),
   Stephen Linton (), and
   Markus Pfeiffer (http://www.morphism.de/~markusp/).
Homepage: https://gap-packages.github.io/anatph/
─────────────────────────────────────────────────────────────────────────────
true

**Comment by markuspf** [comment]
Urgh. That's what I get for not testing properly. I committed a small correction just now (and tested it). Should work now.
