### ISSUE TITLE
Name conflict with xgap

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-packages/anatph#32]
Walrus declares a global function Vertex.  It remarks in a comment that it isn't a good name.  Indeed, it causes a conflict with xgap.  (It might be that Vertex isn't a good choice of name in that package, either, but it's been there for years and other packages like ITC depend on it.)

As Gap.app always loads xgap, and I want walrus to be useable from there, I patched to rename Vertex to WalrusVertex in the GAP included in Gap.app 0.61.

Perhaps it would even be worthwhile prepending Walrus to all the non-externally-facing globals in the package?

**Comment by RussWoodroofe** [comment]
I made a PR for the local problem, but did not try to fix the bigger problem.

**Comment by RussWoodroofe** [comment]
ping?

**Comment by fingolfin** [comment]
I don't think this package is maintained anymore :-(

**Comment by fingolfin** [comment]
Anyway your PR #35 was merged, I'll make a release of this now
