### ISSUE TITLE
PregroupOfFreeProductWithAmalgamation

### ISSUE THREAD

**Issue by markuspf** [gap-packages/anatph#8]
Should be renamed to `PregroupOfFreeProduct` and should be able to

* Accept a pair of group homomorphisms with equal source to make a free product with amalgamation
* Accept a list of pairs of group homomorphisms to make a `k`-ary free product with almagamation

**Comment by markuspf** [comment]
Actually, for amalgamation we should use a new name `PregroupOfFreeProductAmalgamating` or `PregroupOfFreeProductWithAmalgamation`.

**Comment by colva** [comment]
I’d prefer PregroupOfFreeProductWithAmalgamation

Colva
